### ISSUE TITLE
Add username mapping, codehaus=trygvis, github=trygvis

### ISSUE THREAD

**Issue by trygvis** [MojoHaus/svnrepo-gitified-wip#1]

**Comment by Batmat** [comment]
Not sure what you want. I added you to the org, but that was not the same thread.
Cheers

**Comment by acollign** [comment]
Hi @Batmat, I think @trygvis is asking for mapping author and username on a git commit level. As far as I know, this can to be done by rewriting commits to update the username and/or email address.

There is actually a tool meant for that [1] which seems pretty handy. We can also do it with a simple script as described in the github help [2]

[1] https://github.com/davidfokkema/git-rewrite-author
[2] https://help.github.com/articles/changing-author-info/

**Comment by Batmat** [comment]
Yup. But that would be useful if we planned to transform the current repo,
which I personally don't plan to do (see the ml associated thread to
discuss that part).
Cheers
Le 8 avr. 2015 13:09, "Alexandre COLLIGNON" <notifications@github.com> a
écrit :
